spring.main.banner-mode: off
spring:
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  datasource:
    url: jdbc:mysql://localhost:3306/lesson_bank_cards?useSSL=false
    username: root
    password: qwerty2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.connection-timeout: 60000
    hikari.maximum-pool-size: 5


  application:
    name: cards
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071


  #Distributed logging
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      rate: 1


server:
  port: 8083

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
