spring:
  application:
    name: eurekaserver
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071
  #Distributed logging
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      rate: 1


server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'
