spring.main.banner-mode: off
spring:
  application:
    name: accounts
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  datasource:
    url: jdbc:mysql://localhost:3306/lesson_bank_accounts?useSSL=false
    username: root
    password: qwerty2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.connection-timeout: 60000
    hikari.maximum-pool-size: 5

  #Distributed logging
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      rate: 1


  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

info:
  app:
    name: Accounts Microservice
    desciption: CjXonix Bank Account Application
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  url:
    loans: http://127.0.0.1:8082
    cards: http://127.0.0.1:8083
#Resilience patterns [Circuit Breaker pattern, Retry Pattern and Rate Limiter Pattern, Bulk ahead pattern ]
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      detailsForCustomerSupportApp:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      retryCustomerCustomerDetails:
        maxRetryAttempts: 3
        waitDuration: 2000
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      sayHello:
        timeoutDuration: 5000
        limitRefreshPeriod: 5000
        limitForPeriod: 1
