version: "3.8"

services:
  configserver:
    image: cjxonix/configserver
    ports:
      - "8071:8071"
    environment:
      server.port: 8071
    networks:
      - xonix-bank-network

  accounts:
    image: cjxonix/accounts
    ports:
      - "8081:8081"
    environment:
      server.port: 8081
      spring.datasource.url: jdbc:mysql://bank-mysql-db:3306/lesson_bank_accounts?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: qwerty2020
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
    networks:
      - xonix-bank-network
    depends_on:
      - mysql
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  loans:
    image: cjxonix/loans
    ports:
      - "8082:8082"
    environment:
      server.port: 8082
      spring.datasource.url: jdbc:mysql://bank-mysql-db:3306/lesson_bank_loans?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: qwerty2020
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
    networks:
      - xonix-bank-network
    depends_on:
      - mysql
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  cards:
    image: cjxonix/cards
    ports:
      - "8083:8083"
    environment:
      server.port: 8083
      spring.datasource.url: jdbc:mysql://bank-mysql-db:3306/lesson_bank_cards?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: qwerty2020
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
    networks:
      - xonix-bank-network
    depends_on:
      - mysql
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  mysql:
    image: mysql:5.7
    container_name: bank-mysql-db
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    volumes:
      - bank-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty2020
      MYSQL_DATABASE: lesson_bank_cards
    networks:
      - xonix-bank-network

volumes:
  bank-mysql-data:

networks:
  xonix-bank-network:
